# Lab 1 – Basic NumPy Operations - Part A

In [3]:
import numpy as np


##### 2. Create an array starting from 1 to 20 incremented by 3


In [4]:
arr = np.arange(1, 21, 3)
arr


array([ 1,  4,  7, 10, 13, 16, 19])

##### 3. Create a new array of shape (3,) with random numbers between 0 and 1


In [5]:
rand_arr = np.random.rand(3)
rand_arr


array([0.01393908, 0.98339193, 0.09210707])

##### 4. Create a 2D array and perform slicing operations
Array:  
`[[10,20,45], [30,12,16], [42,17,56]]`


In [9]:
A = np.array([[10,20,45],
              [30,12,16],
              [42,17,56]])

first_two_rows = A[:2, :]
last_two_rows = A[1:, :]

first_two_rows, last_two_rows


(array([[10, 20, 45],
        [30, 12, 16]]),
 array([[30, 12, 16],
        [42, 17, 56]]))

##### 5. Create two 2x2 arrays and demonstrate stacking and splitting


In [ ]:
B = np.array([[1,2],
              [3,4]])

C = np.array([[5,6],
              [7,8]])

# Vertical stack
v_stack = np.vstack((B, C))

# Horizontal stack
h_stack = np.hstack((B, C))

# Splitting into smaller arrays
v_split = np.vsplit(v_stack, 2)
h_split = np.hsplit(h_stack, 2)

v_stack, h_stack, v_split, h_split


##### 6. Matrix Multiplication Check
Matrix X (3x3)  
Matrix Y (3x2)  
We check if multiplication is possible and demonstrate a case where it is not.


In [ ]:
X = np.array([[5,7,2],
              [4,5,6],
              [7,4,2]])

Y = np.array([[4,2],
              [6,2],
              [4,2]])

# Multiplication is possible because inner dimensions match (3x3) * (3x2)
XY = np.matmul(X, Y)

# Multiplication is not possible because inner dimensions do not match (3x2) * (3x3)
try:
    np.matmul(Y, X)  # (3x2) * (3x3) → inner dims 2 != 3 → error
except ValueError as e:
    error_message = str(e)

XY, error_message


##### 7. Shape, Dimensions, and Reshaping


In [10]:
x = np.array([2, -1, -8])
y = np.array([3, 1, -2])

shape_x = x.shape
dims_x = x.ndim

# Reshape x to (3,1)
x_reshaped = x.reshape(3,1)
dims_x_reshaped = x_reshaped.ndim

# Reshape y to (3,1)
y_reshaped = y.reshape(3,1)
dims_y_reshaped = y_reshaped.ndim

shape_x, dims_x, dims_x_reshaped, dims_y_reshaped


((3,), 1, 2, 2)

##### 8. Broadcasting Demonstration
Subtracting and multiplying a 3x3 matrix with a 1D array.


In [11]:
M = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

v = np.array([1,2,3])

sub_result = M - v
mul_result = M * v

sub_result, mul_result


(array([[0, 0, 0],
        [3, 3, 3],
        [6, 6, 6]]),
 array([[ 1,  4,  9],
        [ 4, 10, 18],
        [ 7, 16, 27]]))